version: '3'

services:
  # Backend service
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  # Frontend service
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # MongoDB service
  mongo:
    image: "mongo:latest"